---
- hosts: all
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: copy static files into ansible nodes
    copy:
     src: mytestfile
     dest: /home/ubuntu/mystaticfile
  - name: install webserver
    apt: 
     name: apache2
     state: present

  - name: copy dynamoc files into ansible nodes
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
    notify:
     - start webserver

  - name: download internet files into nodes
    get_url:
      url: https://get.jenkins.io/war-stable/2.346.2/jenkins.war
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes
  handlers:
   - name: start webserver
     service: 
      name: apache2
      state: started